debian/tmp/usr/lib/python???/*-packages/pokeradditions/*.py
debian/tmp/usr/lib/python???/*-packages/pokeradditions/pokerfulltables/*.py
debian/tmp/usr/lib/python???/*-packages/pokeradditions/pokerxps/*.py
debian/tmp/usr/lib/python???/*-packages/pokeradditions/auth/*.py
debian/tmp/usr/lib/python???/*-packages/pokeradditions/pokertourneys/*.py
debian/tmp/usr/lib/python???/*-packages/pokeradditions/pokertourneystarts/*.py
debian/tmp/usr/lib/python???/*-packages/pokeradditions/pokerrewards/*.py
debian/tmp/usr/lib/python???/*-packages/pokeradditions/pokerrewards/rewards/*.py
debian/tmp/usr/lib/python???/*-packages/pokeradditions/filters/*.py

debian/tmp/usr/share/poker-network/conf/poker.server.additions.xml
debian/tmp/usr/share/poker-network/conf/poker.bot.additions.xml
