#debian/tmp/usr/lib/python???/*-packages/pokeradditions/*.py
#debian/tmp/usr/lib/python???/*-packages/pokeradditions/pokerfulltables/*.py
#debian/tmp/usr/lib/python???/*-packages/pokeradditions/pokerxps/*.py
#debian/tmp/usr/lib/python???/*-packages/pokeradditions/auth/*.py
#debian/tmp/usr/lib/python???/*-packages/pokeradditions/pokertourneys/*.py
#debian/tmp/usr/lib/python???/*-packages/pokeradditions/pokertourneystarts/*.py
#debian/tmp/usr/lib/python???/*-packages/pokeradditions/pokeruserstats/*.py
#debian/tmp/usr/lib/python???/*-packages/pokeradditions/pokerrewards/*.py
#debian/tmp/usr/lib/python???/*-packages/pokeradditions/pokerrewards/rewards/*.py
#debian/tmp/usr/lib/python???/*-packages/pokeradditions/filters/*.py
#debian/tmp/usr/share/poker-network/conf/poker.server.additions.xml
#debian/tmp/usr/share/poker-network/conf/poker.bot.additions.xml
#debian/tmp/usr/share/poker-network/conf/badwords.txt

README AUTHORS LICENSE AGPLv3 GPLv3 usr/share/doc/python-poker-additions
pokeradditions/conf/badwords.txt pokeradditions/*.xml usr/share/poker-network/conf
pokeradditions/*.py usr/share/pyshared/pokeradditions
pokeradditions/pokerfulltables/*.py usr/share/pyshared/pokeradditions/pokerfulltables
pokeradditions/pokerxps/*.py usr/share/pyshared/pokeradditions/pokerxps
pokeradditions/auth/*.py usr/share/pyshared/pokeradditions/auth
pokeradditions/pokertourneys/*.py usr/share/pyshared/pokeradditions/pokertourneys
pokeradditions/pokertourneystarts/*.py usr/share/pyshared/pokeradditions/pokertourneystarts
pokeradditions/pokeruserstats/*.py usr/share/pyshared/pokeradditions/pokeruserstats
pokeradditions/pokerrewards/*.py usr/share/pyshared/pokeradditions/pokerrewards
pokeradditions/pokerrewards/rewards/*.py usr/share/pyshared/pokeradditions/pokerrewards/rewards
pokeradditions/filters/*.py usr/share/pyshared/pokeradditions/filters
