#!/bin/sh
#
# Copyright (C) 2005 Mekensleep
#
# Mekensleep
# 24 rue vieille du temple
# 75004 Paris
#       licensing@mekensleep.com
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA  02110-1301, USA.
#
# Authors:
#  Loic Dachary <loic@gnu.org>
#

SERVER_CONFIG=${1:-poker.server.xml}
SCHEMA=../database/schema.sql

. ../tests/createdatabase

python -u ../pokernetwork/pokerserver.py ${SERVER_CONFIG} > pokerserver.log 2>&1 &
server_pid=$!
echo "Server now running as process $server_pid with logs in pokerserver.log"
sleep 3 # wait for server to bootstrap
while : 
do
  python -u ../pokernetwork/pokerbot.py poker.bot.xml > pokerbot.log 2>&1 &
  bot_pid=$!
  trap "kill $server_pid $bot_pid 2> /dev/null ; egrep '"'Traceback\|CRITICAL\|ERROR'"' poker{bot,server}.log" SIGINT SIGQUIT EXIT
  echo "Bots now running as process $bot_pid with logs in pokerbot.log"
  wait $bot_pid
exit 0
  if wait $bot_pid
  then
    if grep 'Traceback\|CRITICAL\|ERROR' poker{bot,server}.log
    then
      exit -1
    fi
    sleep 1
  else
    break
  fi
done

