#!/bin/sh
#
# Copyright (C) 2007 Loic Dachary <loic@dachary.org>
#
# This software's license gives you freedom; you can copy, convey,
# propagate, redistribute and/or modify this program under the terms of
# the GNU Affero General Public License (AGPL) as published by the Free
# Software Foundation (FSF), either version 3 of the License, or (at your
# option) any later version of the AGPL published by the FSF.
#
# This program is distributed in the hope that it will be useful, but
# WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU Affero
# General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with this program in a file in the toplevel directory called
# "AGPLv3".  If not, see <http://www.gnu.org/licenses/>.
#
set -e

sh -e ${srcdir}/poker_players_ autoconf | grep yes > /dev/null

DEBCONF=${srcdir}/test_config.dat sh -e ${srcdir}/poker_players_ suggest | grep pokersource.info > /dev/null

sh -e ${srcdir}/poker_players_ config | grep players.label > /dev/null

WGET=${srcdir}/test_wget1 sh -e ${srcdir}/poker_players_ | grep players.value > /dev/null
