#!/bin/sh
#
# Copyright (C) 2007 Loic Dachary <loic@dachary.org>
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA  02110-1301, USA.
#
set -e

sh -e ${srcdir}/poker_traffic_ autoconf | grep yes > /dev/null

DEBCONF=${srcdir}/test_config.dat sh -e ${srcdir}/poker_traffic_ suggest | grep pokersource.info > /dev/null

sh -e ${srcdir}/poker_traffic_ config | grep out.label > /dev/null

WGET=${srcdir}/test_wget1 sh -e ${srcdir}/poker_traffic_ | grep in.value > /dev/null
